version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Prgm-code
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Prgm-code
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 5
    groups:
      frontend:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    reviewers:
      - Prgm-code
    labels:
      - dependencies
      - rust
    open-pull-requests-limit: 5
    groups:
      rust:
        patterns:
          - "*"
